[project]
name = "space-glue"
version = "0.1.0"
description = " Spatial Cognition Exercises â€“ General Language Understanding Evaluation"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []
